name: mlflow-ci-env
channels:
  - defaults
dependencies:
  - python=3.9
  - pip=21.3
  - scikit-learn=1.1.3
  - pandas=1.5.0
  - numpy=1.23.5
  - mlflow=2.9.2 
  - pip:
    - -e . # Jika Anda memiliki package tambahan
